---
- hosts: dvr
  become: true

  handlers:
    - name: Restart containers
      ansible.builtin.command:
        cmd: docker compose --ansi never --progress plain --file docker-compose.yml restart
        chdir: "~/frigate/"
      become: false
      register: temp_compose_up
      changed_when: true

  pre_tasks:
    - name: Include custom configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/../config.yml"
      tags: ['always']

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

  tasks:
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

    - name: Ensure pip is installed.
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install required python libraries.
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Create Frigate folders on Pi.
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      become: false
      with_items:
        - "~/frigate"
        - "~/frigate/mosquitto"
        - "~/frigate/mosquitto/logs"
      register: create_folders

    - name: Copy Frigate files to Pi.
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "~/frigate/{{ item }}"
        mode: '0640'
      become: false
      notify: Restart containers
      with_items:
        - docker-compose.yml
        - frigate.yml
        - mosquitto/mosquitto.conf
        - mosquitto/mqtt-auth.conf
        - mosquitto/mqtt-acl.conf

    # See: https://github.com/ansible-collections/community.docker/pull/586
    - name: Validate Docker Compose file.
      ansible.builtin.command:
        cmd: docker compose --file docker-compose.yml config --quiet
        chdir: "~/frigate/"
      become: false
      changed_when: false

    - name: Start containers
      ansible.builtin.command:
        cmd: docker compose --ansi never --progress plain --file docker-compose.yml up --detach
        chdir: "~/frigate/"
      become: false
      register: temp_compose_up
      changed_when: "'Started' in temp_compose_up.stdout"

    # TODO: This is the right command... but it doesn't seem to be running.
    - name: Encrypt the mosquitto passwords.
      community.docker.docker_container_exec:
        container: mqtt
        command: 'mosquitto_passwd -U /mosquitto/config/mqtt-auth.conf'
      when: frigate_configure_mqtt_broker
      notify: Restart containers
